/*
 * Copyright 2014-2018 Neueda Ltd.
 * 
 * Generated 13:42:16 22/11/18
 */
#pragma once

namespace neueda
{

#define BoeLoginRequestTemplateId 0x37
#define BoeLoginResponseTemplateId 0x24
#define BoeLogoutResponseTemplateId 0x08
#define BoeServerHeartbeatTemplateId 0x09
#define BoeClientHeartbeatTemplateId 0x03
#define BoeReplayCompleteTemplateId 0x13
#define BoeNewOrderTemplateId 0x38
#define BoeCancelOrderTemplateId 0x39
#define BoeModifyOrderTemplateId 0x3A
#define BoeTradeCaptureReportTemplateId 0x3C
#define BoeOrderAcknowledgementTemplateId 0x25
#define BoeOrderRejectedTemplateId 0x26
#define BoeOrderModifiedTemplateId 0x27
#define BoeOrderRestatedTemplateId 0x28
#define BoeUserModifyRejectedTemplateId 0x29
#define BoeOrderCancelledTemplateId 0x2A
#define BoeCancelRejectedTemplateId 0x2B
#define BoeOrderExecutionTemplateId 0x2C
#define BoeTradeCancelCorrectTemplateId 0x2D
#define BoeTradeCaptureReportAcknowledgementTemplateId 0x30
#define BoeTradeCaptureReportRejectTemplateId 0x31
#define BoeTradeCaptureConfirmTemplateId 0x32
#define BoeTradeCaptureReportDeclineTemplateId 0x33

// enum for ReasonCodes
#define BOE_REASONCODES_ADMIN 0
#define BOE_REASONCODES_DUPLICATE_IDENTIFIER 1
#define BOE_REASONCODES_HALTED 2
#define BOE_REASONCODES_INCORRECT_DATA_CENTER 3
#define BOE_REASONCODES_TOO_LATE_TO_CANCEL 4
#define BOE_REASONCODES_ORDER_RATE_THRESHOLD_EXCEEDED 5
#define BOE_REASONCODES_PENDING_PERIODIC_AUCTION 6
#define BOE_REASONCODES_PRICE_EXCEED_CROSS_RANGE 7
#define BOE_REASONCODES_LIQUIDITY_AVAILABLE_EXCEEDS_ORDER_SIZE 8
#define BOE_REASONCODES_RAN_OUT_OF_LIQUIDITY_TO_EXECUTE_AGAINST 9
#define BOE_REASONCODES_CLORDID_DOESNT_MATCH_A_KNOWN_ORDER 10
#define BOE_REASONCODES_CANT_MODIFY_AN_ORDER_THAT_IS_PENDING_FILL 11
#define BOE_REASONCODES_WAITING_FOR_FIRST_TRADE 12
#define BOE_REASONCODES_ROUTING_UNAVAILABLE 13
#define BOE_REASONCODES_ROUTING_ORDER_WOULD_TRADE_THROUGH_AN_AWAY_DESTINATION 14
#define BOE_REASONCODES_USER_REQUESTED 15
#define BOE_REASONCODES_WOULD_WASH 16
#define BOE_REASONCODES_ADD_LIQUIDITY_ONLY_ORDER_WOULD_REMOVE 17
#define BOE_REASONCODES_ORDER_EXPIRED 18
#define BOE_REASONCODES_SYMBOL_NOT_SUPPORTED 19
#define BOE_REASONCODES_UNFORESEEN_REASON 20
#define BOE_REASONCODES_LARGE_IN_SCALE 21
#define BOE_REASONCODES_MARKET_ACCESS_RISK_LIMIT_EXCEEDED 22
#define BOE_REASONCODES_MAX_OPEN_ORDERS_COUNT_EXCEEDED 23
#define BOE_REASONCODES_STATIC_COLLAR_BREACH 24
#define BOE_REASONCODES_RESERVE_RELOAD 25
#define BOE_REASONCODES_RISK_MANAGEMENT_SYMBOL_LEVEL 26
#define BOE_REASONCODES_CROSSED_MARKET 27
#define BOE_REASONCODES_MIFID_II_DOUBLE_CAP_RELATED 28
#define BOE_REASONCODES_ORDER_RECEIVED_BY_CBOE_DURING_REPLAY 29

// enum for LoginResponseStatus
#define BOE_LOGINRESPONSESTATUS_LOGIN_ACCEPTED 0
#define BOE_LOGINRESPONSESTATUS_NOT_AUTHORIZED 1
#define BOE_LOGINRESPONSESTATUS_SESSION_IS_DISABLED 2
#define BOE_LOGINRESPONSESTATUS_SESSION_IN_USE 3
#define BOE_LOGINRESPONSESTATUS_SEQUENCE_AHEAD_OF_LOGIN 4
#define BOE_LOGINRESPONSESTATUS_INVALID_UNIT_IN_LOGIN 5
#define BOE_LOGINRESPONSESTATUS_INVALID_RETURN_BITFIELD_IN_LOGIN 6
#define BOE_LOGINRESPONSESTATUS_INVALID_LOGIN_REQUEST_STRUCTURE 7

// enum for Capacity
#define BOE_CAPACITY_AGENCY 0
#define BOE_CAPACITY_PRINCIPAL 1
#define BOE_CAPACITY_RISKLESS_CAPACITY 2

// enum for RestatementReason
#define BOE_RESTATEMENTREASON_REROUTE 0
#define BOE_RESTATEMENTREASON_LOCKED_IN_CROSS 1
#define BOE_RESTATEMENTREASON_WASH 2
#define BOE_RESTATEMENTREASON_RELOAD 3
#define BOE_RESTATEMENTREASON_LIQUIDITY_UPDATED 4

// enum for LogoutResponseStatus
#define BOE_LOGOUTRESPONSESTATUS_USER_REQUESTED 0
#define BOE_LOGOUTRESPONSESTATUS_END_OF_DAY 1
#define BOE_LOGOUTRESPONSESTATUS_ADMINISTRATIVE 2
#define BOE_LOGOUTRESPONSESTATUS_PROTOCOL_VIOLATION 3

// enum for Side
#define BOE_SIDE_BUY 0
#define BOE_SIDE_SELL 1
#define BOE_SIDE_SELL_SHORT 2
#define BOE_SIDE_SELL_SHORT_EXEMPT 3
#define BOE_SIDE_SELL_UNDISCLOSED 4

// enum for PartyRole
#define BOE_PARTYROLE_EXECUTING_FIRM 0
#define BOE_PARTYROLE_ENTERING_FIRM 1
#define BOE_PARTYROLE_CONTRA_FIRM 2

}; // namespace neueda
