/*
 * Copyright 2014-2018 Neueda Ltd.
 * 
 * Generated 15:32:41 22/11/18
 */
#ifndef BOE_PACKETS_H
#define BOE_PACKETS_H

#include "BoeHeaderPacket.h" 
#include "BoeBitfieldPacket.h"
#include "BoeSideGroupPacket.h"
#include "BoeHeaderPacket.h"
#include "BoeLoginRequestPacket.h"
#include "BoeLoginResponsePacket.h"
#include "BoeLogoutResponsePacket.h"
#include "BoeServerHeartbeatPacket.h"
#include "BoeClientHeartbeatPacket.h"
#include "BoeReplayCompletePacket.h"
#include "BoeNewOrderPacket.h"
#include "BoeCancelOrderPacket.h"
#include "BoeModifyOrderPacket.h"
#include "BoeTradeCaptureReportPacket.h"
#include "BoeOrderAcknowledgementPacket.h"
#include "BoeOrderRejectedPacket.h"
#include "BoeOrderModifiedPacket.h"
#include "BoeOrderRestatedPacket.h"
#include "BoeUserModifyRejectedPacket.h"
#include "BoeOrderCancelledPacket.h"
#include "BoeCancelRejectedPacket.h"
#include "BoeOrderExecutionPacket.h"
#include "BoeTradeCancelCorrectPacket.h"
#include "BoeTradeCaptureReportAcknowledgementPacket.h"
#include "BoeTradeCaptureReportRejectPacket.h"
#include "BoeTradeCaptureConfirmPacket.h"
#include "BoeTradeCaptureReportDeclinePacket.h"
#include "BoeNewOrderBitfieldPacket.h"
#include "BoeCancelOrderBitfieldPacket.h"
#include "BoeModifyOrderBitfieldPacket.h"
#include "BoeTradeCaptureReportBitfieldPacket.h"
#include "BoeOrderAcknowledgementBitfieldPacket.h"
#include "BoeOrderRejectedBitfieldPacket.h"
#include "BoeOrderModifiedBitfieldPacket.h"
#include "BoeOrderRestatedBitfieldPacket.h"
#include "BoeUserModifyRejectedBitfieldPacket.h"
#include "BoeOrderCancelledBitfieldPacket.h"
#include "BoeCancelRejectedBitfieldPacket.h"
#include "BoeOrderExecutionBitfieldPacket.h"
#include "BoeTradeCancelCorrectBitfieldPacket.h"
#include "BoeTradeCaptureReportAcknowledgementBitfieldPacket.h"
#include "BoeTradeCaptureReportAcknowledgementSideGroupPacket.h"
#include "BoeTradeCaptureReportRejectBitfieldPacket.h"
#include "BoeTradeCaptureReportRejectSideGroupPacket.h"
#include "BoeTradeCaptureConfirmBitfieldPacket.h"
#include "BoeTradeCaptureConfirmSideGroupPacket.h"
#include "BoeTradeCaptureReportDeclineBitfieldPacket.h"
#include "BoeTradeCaptureReportDeclineSideGroupPacket.h"

#endif
